
{
  "services": [
    {
      "type": "web",
      "name": "oinio-public-server",
      "env": "node",
      "plan": "free",
      "buildCommand": "npm install",
      "startCommand": "npm start"
    }
  ]
}
